settings:
  username: "itsApurba" # Replace with your username or comment out this line
  # commit_msg: "⚡ Update README with the recent activity"
  # max_lines: 5
  readme_file: "./.github/README.md"